### ISSUE TITLE
Date Issues Due to COVID-19 & Return to Play 

### ISSUE THREAD

**Issue by mattdonders** [HarryShomer/Hockey-Scraper#19]
Because of the delay due to COVID-19 and the return to play protocol, the scraper doesn't detect games after July 1st of the season.

I had oen thought about this and stumbled upon what I believe to be a bug (both in the same code section).

Here is your original code in `nhl.json_schedule` in the `get_dates()` function.
```python
# If the last game is part of the ongoing season then only request the schedule until that day
# We get strange errors if we don't do it like this
if year_to == shared.get_season(datetime.strftime(datetime.today(), "%Y-%m-%d")):
    date_to = '-'.join([str(datetime.today().year), str(datetime.today().month), str(datetime.today().day)])
else:
    date_to = '-'.join([str(int(year_to) + 1), '7', '1'])  # Newest game in sample
```

My first thought was to just change the second date to August 30th - 
```python
[...]
else:
    date_to = '-'.join([str(int(year_to) + 1), '8', '30'])  # Newest game in sample
```

But then I noticed your first line mentions that if the game is in the current season we should only request games until that date, but that can never be possible since you are comparing a string (`year_to`) and an integer (`shared.get_season(datetime.strftime(datetime.today(), "%Y-%m-%d"))`

Let me know if you'd like me to submit a PR against this or how you want to work on fixing it up - maybe a logic if the year detected is 2020?

**Comment by HarryShomer** [comment]
Hey @mattdonders,

To answer your points:

1. Moving the date from July 1st until the end of August make sense to me for the time being. I guess a global pandemic postponing the season into the summer is one edge case I never considered. Also on this note this same logic is used and will need to be changed in shared.get_season. 

2. You are also right about the equality comparing a str to an int. That's a mistake in my part.we can just cast year_to to an int.

So with that said I'm more than happy to accept a PR. I'm currently dealing with some laptop troubles so I might now be able to test this for a few days (writing this from my phone). But the changes outlined here are minor so I'm fine with accepting any PR outright.

Thanks for bringing this to my attention!

Regards,
Harry

**Comment by mattdonders** [comment]
Hey @HarryShomer - sorry to hear about the laptop troubles. 

Tonight I'll open a PR that makes both fixes in all places you mentioned. 

- I will change dates to `YYYY-08-30` in both places. 
- Will also cast `year_to` to an integer to fix that logic.

If you let me know how to run your test suite I can do so locally in my environment as well just to be sure.

**Comment by HarryShomer** [comment]
@mattdonders You can run the test using pytest. Just move over to the `tests` directory and run `pytest`. 

With that said I'm fairly confident that these changes won't break anything so I'll just merge it for now. I'll leave this open until we can confirm it's fine.

**Comment by mattdonders** [comment]
Some of the tests failed because of a timeout from the NHL API.

I also noticed that `pypi` is not updated with this latest version - it still seems to have `1.36.4` which was updated June 15, 2020. Is there something that needs to be triggered to push / build the latest version into there?

Thanks again!

**Comment by HarryShomer** [comment]
Yeah the tests related to the schedule are liable to fail due to timeout issues so not a big deal. Thanks for running them. 

In terms of pypi I will have to load the latest version myself. My computer issues are fixed so I'll do it tonight.

**Comment by HarryShomer** [comment]
So per the NHL [here](https://nhl.nbcsports.com/2020/07/10/new-nhl-critical-dates-calendar-means-an-october-free-agent-frenzy/) the current season should end in October an the next season should begin in December.

I just pushed a commit (47d1fe0) updated the logic to correct for that and refactored some of the code to make everything more explicit and cleaner. Also uploaded new version to pypi.

Will still keep this open in case there are any new developments.
