### ISSUE TITLE
Coordinates not properly showing for goals

### ISSUE THREAD

**Issue by ztandrews** [HarryShomer/Hockey-Scraper#32]
Not sure if this is related to the new updates with the NHL's data, or just because it's pre-season,  but I noticed that the scraper is not populating the coordinates field for most goals so far this pre-season. I've attached a screenshot of the issue. The dataframe I'm running this on is the PBP data from each game on 9/28. It's normal for these other events (Stop, Pend, etc.) to have null coordinates, but that many goals not having proper coordinates seems like an issue possibly. Just wanted to raise awareness to this
<img width="245" alt="image" src="https://github.com/HarryShomer/Hockey-Scraper/assets/68918006/df07eb2b-1aa5-4401-9b4b-ed4dc1080d72">

**Comment by ztandrews** [comment]
Furthermore, I'm seeing for GOAL events that the Ev_Team column is being populated by the scoring players jersey number rather than the team. Interesting
<img width="757" alt="image" src="https://github.com/HarryShomer/Hockey-Scraper/assets/68918006/a89e7f4a-a26f-4e6b-85d3-0f0693c4ed75">

**Comment by HarryShomer** [comment]
Hey Zach,

The coordinate numbers seem better now. Though there are still a few instances of player numbers  populating the ev team column. Tbh, I'm going to chalk this up to it being the preseason. The data has always been a little wonky for preseason games. For the regular season games I've looked at everything has looked ok.
