### ISSUE TITLE
Error parsing Json pbp for game X 'period'

### ISSUE THREAD

**Issue by MoonLearning** [HarryShomer/Hockey-Scraper#36]
Hi,

I have this  'period' error whenever trying to scrap a game:

eg:

running:
hockey_scraper.scrape_games([2023020002], True)

Scraping Game  2023020002 2023-10-10
Error: Error parsing Json pbp for game 2023020002 'period'
Warning: Using espn for pbp
Error: Espn pbp for game 2023-10-10 PIT CHI is either not there or can't be obtained

Thanks,

**Comment by HarryShomer** [comment]
Hey @MoonLearning , sorry for the silence, I just saw this.

I likely won't have time to look into this until the summer. Quite busy atm. 

If you are or anyone else want to take a stab at it I'll happily merge any merge request.

**Comment by JB13** [comment]
Hey Harry, I managed to hack together a fix last here: https://github.com/HarryShomer/Hockey-Scraper/pull/37. Unsure if there's more "downstream" effort required, but it should unblock a decent amount of people.

**Comment by HarryShomer** [comment]
Fixed in #37
